# Generated by Django 5.2.5 on 2025-10-31 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(db_index=True, max_length=8, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('cost', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['char'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('url', models.SlugField(blank=True, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='box_managem_name_4ea8eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(db_index=True, max_length=15, unique=True)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('artist', models.CharField(db_index=True, max_length=50)),
                ('spotify_url', models.URLField(blank=True, max_length=255)),
                ('deezer_url', models.URLField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('n_deposits', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['title', 'artist'],
                'indexes': [models.Index(fields=['title', 'artist'], name='box_managem_title_09563f_idx'), models.Index(fields=['song_id'], name='box_managem_song_id_4565e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='box_management.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='box_management.song')),
            ],
            options={
                'ordering': ['-deposited_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_type', models.CharField(choices=[('main', 'Main'), ('revealed', 'Revealed')], default='revealed', max_length=8)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='box_management.deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['user', 'deposit'], name='box_managem_user_id_a616e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'deposit'), name='unique_discovery_per_user_and_deposit')],
            },
        ),
        migrations.CreateModel(
            name='EmojiRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='box_management.emoji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_rights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='box_managem_user_id_8fa6aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'emoji'), name='unique_user_emoji_right')],
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dist_location', models.PositiveIntegerField(default=100)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='box_management.box')),
            ],
            options={
                'indexes': [models.Index(fields=['box'], name='box_managem_box_id_d32f35_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='box_management.deposit')),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reactions', to='box_management.emoji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['deposit', 'emoji'], name='box_managem_deposit_625eaa_idx'), models.Index(fields=['user', 'deposit'], name='box_managem_user_id_b257ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'deposit'), name='unique_reaction_per_user_and_deposit')],
            },
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['box', 'deposited_at'], name='box_managem_box_id_1415c3_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['song', 'deposited_at'], name='box_managem_song_id_93f78b_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'deposited_at'], name='box_managem_user_id_e7afb2_idx'),
        ),
    ]
