# Generated by Django 5.2.5 on 2025-11-18 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='public_key',
            field=models.CharField(db_index=True, default=1234, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['public_key'], name='box_managem_public__47a7ad_idx'),
        ),
    ]
