# Generated by Django 5.2.5 on 2026-02-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0002_deposit_public_key_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredsong',
            name='place_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discovered_song_places', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='discoveredsong',
            name='place_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='discoveredsong',
            index=models.Index(fields=['place_content_type', 'place_object_id'], name='box_managem_place_c_c4a6d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='discoveredsong',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('place_content_type__isnull', True), ('place_object_id__isnull', True)), models.Q(('place_content_type__isnull', False), ('place_object_id__isnull', False)), _connector='OR'), name='discovery_place_both_null_or_filled'),
        ),
    ]
