# Generated by Django 5.2.5 on 2026-02-03 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0003_discoveredsong_place_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discoveredsong',
            name='discovery_place_both_null_or_filled',
        ),
        migrations.RemoveIndex(
            model_name='discoveredsong',
            name='box_managem_place_c_c4a6d8_idx',
        ),
        migrations.RemoveField(
            model_name='discoveredsong',
            name='place_content_type',
        ),
        migrations.RemoveField(
            model_name='discoveredsong',
            name='place_object_id',
        ),
        migrations.AddField(
            model_name='discoveredsong',
            name='context',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('profile', 'Profile')], db_index=True, max_length=7, null=True),
        ),
        migrations.AddIndex(
            model_name='discoveredsong',
            index=models.Index(fields=['context'], name='box_managem_context_80ff4c_idx'),
        ),
    ]
