# Generated by Django 5.2.5 on 2026-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0004_remove_discoveredsong_discovery_place_both_null_or_filled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredsong',
            name='context',
            field=models.CharField(choices=[('box', 'Box'), ('profile', 'Profile')], db_index=True, default='box', max_length=10),
        ),
    ]
