# Generated by Django 5.2.5 on 2026-03-19 16:24

import box_management.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0005_alter_discoveredsong_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('background_picture', models.ImageField(blank=True, null=True, upload_to=box_management.models.Client.background_picture_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_per_user_and_deposit',
        ),
        migrations.RemoveField(
            model_name='box',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='box_management.emoji'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'deposit', 'emoji'), name='uniq_user_deposit_emoji'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='box_managem_name_6020f4_idx'),
        ),
        migrations.AddField(
            model_name='box',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='box_management.client'),
        ),
    ]
