# Generated by Django 5.2.5 on 2026-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0006_client_alter_reaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['slug'], name='box_managem_slug_6f5ebc_idx'),
        ),
    ]
