# Generated by Django 5.2.5 on 2026-03-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0007_client_slug_client_box_managem_slug_6f5ebc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('link', models.URLField(max_length=2048)),
                ('short_text', models.CharField(blank=True, help_text='Short preview text, maximum 300 characters.', max_length=300)),
                ('cover_image', models.URLField(blank=True, help_text='Remote URL of the cover image.', max_length=2048)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_authored', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='box_management.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='box_managem_client__fd727f_idx'), models.Index(fields=['client', 'created_at'], name='box_managem_client__4c5ecb_idx'), models.Index(fields=['client', 'published_at'], name='box_managem_client__c95ee0_idx'), models.Index(fields=['author'], name='box_managem_author__55a569_idx'), models.Index(fields=['status'], name='box_managem_status_b729c4_idx'), models.Index(fields=['title'], name='box_managem_title_a09cba_idx')],
            },
        ),
    ]
