# Generated by Django 5.2.5 on 2026-03-29 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0009_alter_article_link_alter_article_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='display_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='display_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='display_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['client', 'display_start_date'], name='box_managem_client__694773_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['client', 'display_end_date'], name='box_managem_client__283a9e_idx'),
        ),
    ]
