# Generated by Django 5.2.5 on 2026-03-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0010_article_display_end_date_article_display_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favicon',
            field=models.URLField(blank=True, help_text='Remote URL of the favicon.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=models.CharField(blank=True, help_text='Article text, maximum 1000 characters.', max_length=1000),
        ),
    ]
