# Generated by Django 5.2.5 on 2026-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0012_alter_article_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_text',
            field=models.CharField(blank=True, help_text='Article text, maximum 10000 characters.', max_length=10000),
        ),
    ]
