# Generated by Django 5.2.5 on 2026-03-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0013_alter_article_short_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncitationPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Phrase affichée sous la barre de recherche pendant la période choisie.', max_length=100)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incitation_phrases', to='box_management.client')),
            ],
            options={
                'ordering': ['start_date', 'created_at'],
                'indexes': [models.Index(fields=['client', 'start_date'], name='box_managem_client__e14712_idx'), models.Index(fields=['client', 'end_date'], name='box_managem_client__113797_idx'), models.Index(fields=['client', 'created_at'], name='box_managem_client__d2e90c_idx')],
            },
        ),
    ]
