# Generated by Django 5.2.5 on 2026-04-01 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0014_incitationphrase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('normalized_text', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('published', 'Published'), ('quarantined', 'Quarantined'), ('removed_moderation', 'Removed by moderation'), ('deleted_by_author', 'Deleted by author')], db_index=True, default='published', max_length=32)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('deposit_public_key', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('deposit_box_name', models.CharField(blank=True, default='', max_length=100)),
                ('deposit_box_url', models.CharField(blank=True, default='', max_length=100)),
                ('deposit_deleted', models.BooleanField(db_index=True, default=False)),
                ('deposit_owner_user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('deposit_owner_username', models.CharField(blank=True, default='', max_length=150)),
                ('author_username', models.CharField(blank=True, default='', max_length=150)),
                ('author_display_name', models.CharField(blank=True, default='', max_length=150)),
                ('author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('author_avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('author_user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='box_management.client')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='box_management.deposit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_public_key', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('target_owner_user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('target_owner_username', models.CharField(blank=True, default='', max_length=150)),
                ('text', models.CharField(blank=True, default='', max_length=100)),
                ('normalized_text', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('reason_code', models.CharField(db_index=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('author_user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_attempt_logs', to='box_management.client')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_attempt_logs', to='box_management.deposit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_attempt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_code', models.CharField(db_index=True, max_length=64)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('internal_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_decisions', to='box_management.comment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(db_index=True, max_length=64)),
                ('free_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reporter_username', models.CharField(blank=True, default='', max_length=150)),
                ('reporter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='box_management.comment')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommentUserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('comment_mute_24h', 'Comment mute 24h'), ('comment_mute_7d', 'Comment mute 7d'), ('comment_ban', 'Comment ban')], db_index=True, max_length=32)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('internal_note', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_restrictions', to='box_management.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comment_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['client', 'status', 'created_at'], name='box_managem_client__931c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['deposit', 'status', 'created_at'], name='box_managem_deposit_ea7936_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='box_managem_user_id_7d486c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['deposit_owner_user_id', 'created_at'], name='box_managem_deposit_02ada1_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('deposit', 'user'), name='unique_comment_per_user_and_deposit'),
        ),
        migrations.AddIndex(
            model_name='commentattemptlog',
            index=models.Index(fields=['client', 'reason_code', 'created_at'], name='box_managem_client__41360b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentattemptlog',
            index=models.Index(fields=['user', 'reason_code', 'created_at'], name='box_managem_user_id_df999a_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmoderationdecision',
            index=models.Index(fields=['decision_code', 'created_at'], name='box_managem_decisio_cff82c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmoderationdecision',
            index=models.Index(fields=['reason_code', 'created_at'], name='box_managem_reason__b23ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['reason_code', 'created_at'], name='box_managem_reason__3aa549_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reporter'), name='unique_comment_report_per_user'),
        ),
        migrations.AddIndex(
            model_name='commentuserrestriction',
            index=models.Index(fields=['client', 'user', 'created_at'], name='box_managem_client__64b983_idx'),
        ),
        migrations.AddIndex(
            model_name='commentuserrestriction',
            index=models.Index(fields=['client', 'starts_at', 'ends_at'], name='box_managem_client__5c6707_idx'),
        ),
    ]
