# Generated by Django 5.2.5 on 2026-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0015_comment_commentattemptlog_commentmoderationdecision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
