# Generated by Django 5.2.5 on 2026-04-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0016_song_accent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
    ]
