# Generated by Django 5.2.5 on 2026-04-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0017_alter_song_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url_small',
            field=models.URLField(blank=True, default=''),
        ),
    ]
