# Generated by Django 5.2.5 on 2026-04-10 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0018_song_image_url_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, db_index=True, help_text='11 chiffres. Laisse vide pour générer automatiquement un slug.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Le slug du sticker doit contenir exactement 11 chiffres.', regex='^\\d{11}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stickers', to='box_management.box')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['slug'], name='box_managem_slug_86ea3b_idx'), models.Index(fields=['is_active', 'created_at'], name='box_managem_is_acti_c53832_idx')],
            },
        ),
    ]
