# Generated by Django 5.2.5 on 2026-04-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0019_sticker'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sticker',
            name='box_managem_is_acti_c53832_idx',
        ),
        migrations.AddField(
            model_name='sticker',
            name='assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stickers', to='box_management.client'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='status',
            field=models.CharField(choices=[('created', 'Créé'), ('generated', 'QR généré'), ('downloaded', 'Téléchargé'), ('assigned', 'Assigné')], db_index=True, default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stickers', to='box_management.box'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['client', 'status'], name='box_managem_client__e6400c_idx'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['client', 'is_active', 'created_at'], name='box_managem_client__cea614_idx'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['client', 'qr_generated_at'], name='box_managem_client__bf4c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['client', 'downloaded_at'], name='box_managem_client__c64f30_idx'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['client', 'assigned_at'], name='box_managem_client__97fecb_idx'),
        ),
    ]
