# Generated by Django 5.2.5 on 2026-04-10 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0020_remove_sticker_box_managem_is_acti_c53832_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, editable=False, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le slug du lien doit contenir exactement 15 caractères alphanumériques minuscules sans caractères ambigus.', regex='^[abcdefghjkmnpqrstuvwxyz23456789]{15}$')])),
                ('anonymous_view_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('deposit_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='discoveredsong',
            name='link_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_discoveries_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discoveredsong',
            name='context',
            field=models.CharField(choices=[('box', 'Box'), ('profile', 'Profile'), ('link', 'Link')], db_index=True, default='box', max_length=10),
        ),
        migrations.AddIndex(
            model_name='discoveredsong',
            index=models.Index(fields=['link_sender'], name='box_managem_link_se_1d24a3_idx'),
        ),
        migrations.AddField(
            model_name='link',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links', to='box_management.deposit'),
        ),
        migrations.AddField(
            model_name='link',
            name='opened_by_users',
            field=models.ManyToManyField(blank=True, related_name='opened_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['slug'], name='box_managem_slug_31fb2d_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['created_by', 'created_at'], name='box_managem_created_063d53_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['expires_at'], name='box_managem_expires_992711_idx'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('deposit', 'created_by'), name='unique_link_per_deposit_and_creator'),
        ),
    ]
