# Generated by Django 5.2.5 on 2026-04-10 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0021_link_discoveredsong_link_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('box', 'Box'), ('favorite', 'Favorite')], db_index=True, default='box', max_length=16),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='box_management.box'),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le slug du lien doit contenir exactement 15 caractères alphanumériques minuscules sans caractères ambigus.', regex='^[abcdefghjkmnpqrstuvwxyz23456789]{15}$')]),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['deposit_type', 'deposited_at'], name='box_managem_deposit_da79a5_idx'),
        ),
    ]
