# Generated by Django 5.2.5 on 2026-04-11 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0022_deposit_deposit_type_alter_deposit_box_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='pin_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pin_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pin_points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('box', 'Box'), ('favorite', 'Favorite'), ('pinned', 'Pinned')], db_index=True, default='box', max_length=16),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['deposit_type', 'box', 'pin_expires_at'], name='box_managem_deposit_bb58ad_idx'),
        ),
    ]
