# Generated by Django 5.2.5 on 2026-04-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0023_deposit_pin_duration_minutes_deposit_pin_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongProviderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('not_found', 'Not found'), ('pending', 'Pending')], db_index=True, default='pending', max_length=16)),
                ('provider_track_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_url', models.URLField(blank=True, default='', max_length=255)),
                ('provider_uri', models.CharField(blank=True, default='', max_length=255)),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title', 'public_key']},
        ),
        migrations.RemoveIndex(
            model_name='song',
            name='box_managem_title_09563f_idx',
        ),
        migrations.RemoveIndex(
            model_name='song',
            name='box_managem_song_id_4565e2_idx',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_id',
            new_name='public_key',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='deezer_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_url',
        ),
        migrations.AddField(
            model_name='song',
            name='artists_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='song',
            name='isrc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url_small',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='box_managem_title_06ef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['public_key'], name='box_managem_public__dc9320_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['isrc'], name='box_managem_isrc_2e2cc8_idx'),
        ),
        migrations.AddField(
            model_name='songproviderlink',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='box_management.song'),
        ),
        migrations.AddIndex(
            model_name='songproviderlink',
            index=models.Index(fields=['provider_code', 'provider_track_id'], name='box_managem_provide_445ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='songproviderlink',
            index=models.Index(fields=['song', 'provider_code'], name='box_managem_song_id_a95be5_idx'),
        ),
        migrations.AddIndex(
            model_name='songproviderlink',
            index=models.Index(fields=['provider_code', 'status'], name='box_managem_provide_7c4b21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='songproviderlink',
            unique_together={('song', 'provider_code')},
        ),
    ]
