# Generated by Django 5.2.5 on 2026-04-18 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0024_songproviderlink_alter_song_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='uniq_user_deposit_emoji',
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'deposit'), name='uniq_user_deposit_reaction'),
        ),
    ]
