# Generated by Django 5.2.5 on 2026-04-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0025_remove_reaction_uniq_user_deposit_emoji_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='box_management.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expires_at', '-id'],
                'indexes': [models.Index(fields=['user', 'box'], name='box_managem_user_id_3e762a_idx'), models.Index(fields=['expires_at'], name='box_managem_expires_71a775_idx')],
            },
        ),
    ]
