# Generated by Django 5.2.13 on 2026-04-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0026_boxsession"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="unique_comment_per_user_and_deposit",
        ),
        migrations.AddField(
            model_name="comment",
            name="reply_deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reply_comments",
                to="box_management.deposit",
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="deposit_type",
            field=models.CharField(
                choices=[
                    ("box", "Box"),
                    ("favorite", "Favorite"),
                    ("pinned", "Pinned"),
                    ("comment", "Comment"),
                ],
                db_index=True,
                default="box",
                max_length=16,
            ),
        ),
    ]
