# Generated by Django 5.2.14 on 2026-05-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "box_management",
            "0027_remove_comment_unique_comment_per_user_and_deposit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="boxsession",
            name="deposit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="box_sessions_as_session_deposit",
                to="box_management.deposit",
            ),
        ),
    ]
