# Generated by Django 6.0.5 on 2026-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0028_boxsession_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxsession",
            name="deposit_points_balance_after",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boxsession",
            name="deposit_points_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boxsession",
            name="deposit_successes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
