# Generated by Django 6.0.6 on 2026-06-24 20:19

import box_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0029_boxsession_deposit_points_balance_after_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StickerTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "svg_file",
                    models.FileField(
                        upload_to=box_management.models.sticker_template_upload_to
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sticker_templates",
                        to="box_management.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="box_managem_is_acti_f108d0_idx"
                    ),
                    models.Index(fields=["slug"], name="box_managem_slug_9e2801_idx"),
                ],
            },
        ),
    ]
