# Generated by Django 6.0.6 on 2026-06-29 14:48

import box_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0030_stickertemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "color_space",
                    models.CharField(choices=[("CMYK", "CMYK")], max_length=16),
                ),
                (
                    "icc_file",
                    models.FileField(
                        upload_to=box_management.models.color_profile_upload_to
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["color_space", "is_active", "is_default"],
                        name="box_managem_color_s_762b8e_idx",
                    ),
                    models.Index(fields=["slug"], name="box_managem_slug_4df9b0_idx"),
                ],
            },
        ),
    ]
