# Generated by Django 6.0.6 on 2026-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0031_colorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="require_loc",
            field=models.BooleanField(default=True),
        ),
    ]
