# Generated by Django 5.2.5 on 2026-03-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('box_management', '0008_article'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='box_management.client'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_role',
            field=models.CharField(blank=True, choices=[('client_owner', 'Client owner'), ('client_editor', 'Client editor')], db_index=True, default='', help_text='Role of the user in the client portal.', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portal_status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Access status for the client portal.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['client'], name='users_custo_client__d5cf21_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['client_role'], name='users_custo_client__73ee8e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['portal_status'], name='users_custo_portal__8b6c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['client', 'client_role'], name='users_custo_client__20768f_idx'),
        ),
    ]
