# Generated by Django 5.2.5 on 2026-03-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_client_and_more'),
        ('users', '0002_guest_fields'),
    ]

    operations = [
    ]
