# Generated by Django 5.2.5 on 2026-04-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('box_management', '0022_deposit_deposit_type_alter_deposit_box_and_more'),
        ('users', '0003_merge_20260331_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_users', to='box_management.deposit'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['favorite_deposit'], name='users_custo_favorit_5a2dad_idx'),
        ),
    ]
