# Generated by Django 5.2.5 on 2026-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_preferred_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_platform',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
