# Generated by Django 5.2.5 on 2026-04-18 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_preferred_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(db_index=True, max_length=32)),
                ('provider_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider_code'], name='users_userp_user_id_9d50ba_idx'), models.Index(fields=['provider_code', 'is_active'], name='users_userp_provide_f831be_idx')],
                'unique_together': {('user', 'provider_code')},
            },
        ),
    ]
