# Generated by Django 5.2.13 on 2026-04-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userproviderconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="allow_private_message_requests",
            field=models.BooleanField(default=True),
        ),
    ]
