# Generated by Django 5.2.13 on 2026-04-29 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_allow_private_message_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["follower"], name="users_userf_followe_2b72fd_idx"
                    ),
                    models.Index(
                        fields=["following"], name="users_userf_followi_fd7511_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_userf_created_1a71ec_idx"
                    ),
                    models.Index(
                        fields=["following", "created_at"],
                        name="users_userf_followi_e6569c_idx",
                    ),
                    models.Index(
                        fields=["follower", "created_at"],
                        name="users_userf_followe_271310_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "following"),
                        name="users_follow_unique_pair",
                    )
                ],
            },
        ),
    ]
