# Generated by Django 5.2.5 on 2026-04-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deezer', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeezerToken',
        ),
    ]
