# Generated by Django 5.2.13 on 2026-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="user_a_last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="user_b_last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
